name: Try building ghc
on: 
  workflow_dispatch:
    inputs:
      compilation-flags:
          required: true
          type: string
      target-version:
          required: true
          type: string

jobs:

  build:
    runs-on: macos-latest
    steps:
      - name: setup ghcup and homebrew
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
          ghcup install ghc 9.4.5
          source /Users/runner/.ghcup/env

          # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # brew install autoconf automake python sphinx-doc
          # export PATH="/opt/homebrew/opt/sphinx-doc/bin:$PATH"

      - name: build
        run: |
          ghcup compile ghc -v ${{ inputs.target-version }} -b 9.4.5 ${{ inputs.compilation-flags }} -x aarch64-apple-darwin 


