name: Build and upload artifacts
on: 
  push:
    branches:
      - 'gh-actions'
    paths:
      - '.github/workflows/release.yml'
    
    # tags:
      # - 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  build-upload-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          fast: false
          pedantic: false
          test: false
          stack-arguments: -j2 --local-bin-path=$(pwd) --copy-bins --ghc-options=-O2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: schedule-maker
          name: schedule-maker-ubuntu
          if-no-files-found: error

  build-upload-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          fast: false
          pedantic: false
          test: false
          stack-arguments: -j3 --local-bin-path=$(pwd) --copy-bins --ghc-options=-O2

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: schedule-maker
          name: schedule-maker-macos
          if-no-files-found: error

  build-upload-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies (Windows)
        uses: actions/cache@v3
        with:
          path: C:\sr # 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('schedule-maker.cabal') }}

      - uses: freckle/stack-action@v4
        with: 
          fast: false
          pedantic: false
          test: false
          stack-arguments: -j2 --flag hexpat:bundle --local-bin-path=$(pwd) --copy-bins --ghc-options=-O2
      - run: ls -R
        shell: bash

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: schedule-maker.exe
          name: schedule-maker-windows
          if-no-files-found: error

  create-release:
    runs-on: ubuntu-latest
    needs: 
      - build-upload-ubuntu
      - build-upload-macos
      - build-upload-windows
    steps:
      - uses: actions/download-artifact@v3

      - name: Check artifacts
        run: ls -R

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            schedule-maker*/**
          name: bins
          if-no-files-found: error
