name: test-gh-actions
on:
  pull_request:
    paths:
      - '**.hs'
      - 'stack.yaml'
      - 'package.yaml'
      - '**.cabal'
  push:
    branches:
      - 'gh-actions'
    paths:
      - '**.hs'
      - 'stack.yaml'
      - 'package.yaml'
      - '**.cabal'
jobs:

  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/hlint-setup@v1
      - uses: haskell/actions/hlint-run@v2 

  fourmolu:
    runs-on: ubuntu-latest
    needs: hlint
    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/run-fourmolu@v9
        with:
          # Only check the format of .hs in any directory inside cwd but not cwd.
          pattern: |
            */**/*.hs

  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: fourmolu
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          stack-arguments: --ghc-options -j8
          pedantic: false

  test-win:
    runs-on: windows-latest
    needs: fourmolu
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          stack-arguments: --flag hexpat:bundle --ghc-options -j8
          pedantic: false
