name: test-gh-actions
on:
  push:
    branches:
      - 'gh-actions'
    paths:
      - '**.hs'
      - 'stack.yaml'
      - 'package.yaml'
      - '**.cabal'
jobs:
  test-unix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          stack-arguments: --ghc-options -j8
          pedantic: false

  test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        with: 
          stack-arguments: --flag hexpat:bundle --ghc-options -j8
          pedantic: false
