name: Update README with schedule-maker-exe --help
on:
  push:
    branches:
      - gh-actions
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        name: Build exe
        with:
          fast: true
          pedantic: false
          test: false
          stack-arguments: --exec "stack run -- --help" > out.txt

      - name: Set $CONTENT for text replacement
        run: | 
          {
            echo 'CONTENT<<EOF'
            cat out.txt
            echo EOF
          } >> $GITHUB_ENV

      - name: Update README.md (Find and Replace)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '<!-- REPLACE_EXE_HELP -->\n```[a-z]*\n[\s\S]*?\n```\n'
          include: README.md
          regex: true
          replace: |
              <!-- REPLACE_EXE_HELP -->
              ```
              ${{ env.CONTENT }}
              ```
      - name: Add, commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "[Bot] update README content"
          add: README.md
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
