name: Update README Help
on:
  push:
    branches:
      - gh-actions
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: freckle/stack-action@v4
        name: Build exe
        with:
          fast: true
          pedantic: false
          test: false
          stack-arguments: --copy-bins --exec "stack run -- --help" > out.txt

      - name: Set env
        run: | 
          {
            echo 'CONTENT<<EOF'
            cat out.txt
            echo EOF
          } >> $GITHUB_ENV

      - name: Update README.md (Find and Replace)
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '<!-- REPLACE -->\n```[a-z]*\n[\s\S]*?\n```'
          include: README.md
          regex: true
          replace: |
            ```
            ${{ env.CONTENT }}
            ```
      - name: get info
        run: | 
          ls -a /home/runner/.local/bin/
          ls -a
          echo $CONTENT
          cat README.md
          git status

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "[Bot] update README content"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}          
